---
- name: deploy the php
  hosts: all
  become: yes
  tasks:
    - name: Installing "apache2" 
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: latest
    - name: Installing "php" 
      ansible.builtin.apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        update_cache: yes
        state: latest
    - name: coping the php.info file to node
      ansible.builtin.copy:
        src: php.info
        dest: /var/www/html/info.php
        follow: yes